// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzqnoedruggshfpdeqkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6cW5vZWRydWdnc2hmcGRlcWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTI0MTYsImV4cCI6MjA2NjQ4ODQxNn0.rDubmkCxgad7uzs7aNLe2Hpau7WFNHRI9snCUh65s8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});